# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4254c9a91df9c57277c3b6dc40b7074fed3424c5cc8a9f13fd62d60ec164ee1f0404381359c031085f64a6f97c3a4cf7421db18c2aa0f8b7b167711c5ed61710

test:
  secret_key_base: 56769b2fad35ce8a304ac4ff2addaa52e60ee2d66cedcbeb0ca93033259c6af98c52719dc8f4da98ed95735a6382c959db60e593ff3c0346b1153ce0098af626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
